spring:
    application:
        name: springboot-katharsis
    datasource: 
        url: jdbc:mysql://localhost:3306/spring-boot-db
        username: root
        password: makhir
server:
    context-path: /makhir
    port: 9090
katharsis:
    resourcePackage: com.makhir.springboot.katharsis
    domainName: http://localhost:9090/makhir
    pathPrefix: /api

logging:
    level:
        root: DEBUG
        org:
            springframework:
                security: DEBUG
                web: DEBUG
            hibernate: DEBUG
        com:
            makhir:
                springboot:
                    katharsis: DEBUG
        io:
           katharsis: DEBUG
 
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
        file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '/Users/makhir/work/development/workspace/log/springboot-katharsis.log'